# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd76768e21df428564a3cd28da87182f0e1c3329cf08a7a9af0f5072933daceac8c1095155c709eef75a08f8c039745b00e02c1991b5cfa73f49d26c1be50259

test:
  secret_key_base: c069f1c70390865f63ae46c7da126bf81349d731340058b934f1d24cb52be8eed02e5b408a9b931b753f3b368339c32cb35e640f4a39d729af769728c0674453

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
